env:
      TERM: xterm

window:
  padding:
    x: 0
    y: 0
  startup_mode: Maximized
  title: Alacritty
  class:
    instance: Alacritty
    general: Alacritty

scrolling:
  history: 5000

font:
  size: 12.0
  offset:
    x: 0
    y: 0

draw_bold_text_with_bright_colors: true

background_opacity: 0.8

mouse:
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }

url:
    program: xdg-open
    args: []

key_bindings:
  - { key: V,        mods: Control|Shift, action: Paste            }
  - { key: C,        mods: Control|Shift, action: Copy             }
  - { key: Insert,   mods: Shift,         action: PasteSelection   }
  - { key: Key0,     mods: Control,       action: ResetFontSize    }
  - { key: Equals,   mods: Control,       action: IncreaseFontSize }
  - { key: Minus,    mods: Control,       action: DecreaseFontSize }

  - { key: Paste,                    action: Paste                            }
  - { key: Copy,                     action: Copy                             }
  - { key: L,         mods: Control, action: ClearLogNotice                   }
  - { key: L,         mods: Control, chars: "\x0c"                            }
  - { key: PageUp,    mods: Shift,   action: ScrollPageUp,   mode: ~Alt       }
  - { key: PageDown,  mods: Shift,   action: ScrollPageDown, mode: ~Alt       }
  - { key: Home,      mods: Shift,   action: ScrollToTop,    mode: ~Alt       }
  - { key: End,       mods: Shift,   action: ScrollToBottom, mode: ~Alt       }
